### ISSUE TITLE
What is unique event id for continuous alert

### ISSUE THREAD

**Issue by choonho** [cloudforet-io/plugin-cisco-appdynamics-mon-webhook#1]
When an event (or alert) is created, there is a continuous events which status is changing like "Open" -> "Ongoing" -> "Cancel".

How can I know these separated three events is related with single alert.
a.k.a what is primary key for related events?

~~~
class EventInfo {
  EventType eventType
  long id
  String guid
  String eventTypeKey
  Date eventTime
  String displayName
  String summaryMessage
  String eventMessage
  EntityInfo application
  EntityInfo tier
  EntityInfo node
  EntityInfo db
  List<EntityInfo> affectedEntities
  boolean healthRuleEvent
  EntityInfo anomaly // * Only defined in case of anomaly event
  EntityInfo healthRule // * Only defined when healthRuleEvent == true
  EntityInfo incident // * Only defined when healthRuleEvent == true
  boolean healthRuleViolationEvent
  NotificationSeverity severity
  ImageInfo severityImage
  boolean btPerformanceEvent // * true when eventType matches one of the BT performance event types
  String deepLink
}
~~~

**Comment by choonho** [comment]
# AppDynamics Events

![image](https://user-images.githubusercontent.com/3993088/225489346-4d8763f7-b868-4b14-9bf1-788bbb3ebb81.png)

# Cloudforet Alert

## Want to change ***Title***

* Create single Alert event instead of consecutive separated events.

| Title | As-Is               | To-Be              |
| ---   | ---                   | ---                   |
| Rule | $event.displayName | Same with AppDynamics Console (Events.Type) |
| Example | New Critical Health Rule Violation | Health Rule Violation Started - Critical |


### As-Is 

![image](https://user-images.githubusercontent.com/3993088/225489597-a8da4f93-8c6b-4fc2-ba51-8d97d9d73270.png)

### To-Be

![image](https://user-images.githubusercontent.com/3993088/225491768-fff20dff-2f2c-4098-9cee-5cfb77094fd4.png)

## Want to append ***Timeline***

![image](https://user-images.githubusercontent.com/3993088/225492560-346be313-470c-40d5-9080-d344918ef97b.png)

### As-Is

* Because there is 3 separated events, there is only one ***Pushed Event***.

![image](https://user-images.githubusercontent.com/3993088/225492709-153bc29c-c351-4e13-9775-4baf4939717b.png)

### To-Be

* If you merge 3 separated events into one single event, the ***Pushed Event*** will be like below,

![image](https://user-images.githubusercontent.com/3993088/225493248-3ce72d01-bd3c-437e-8c9e-a730c9e078d1.png)

* To implement this one, we need primary key of separated events.
* There is ***event_key*** in the Cloudforet, which means this event is related with other events if ***event_key*** is same.
* Now we use this value ${latestEvent.id}, but need some new!

**Comment by choonho** [comment]
# Update of Payload 

![image](https://user-images.githubusercontent.com/3993088/225494168-7f88bd30-56e5-4735-8a35-4059a6d8a647.png)

* This is wrong implementation of HTTP Request Template, the result of **As-Is**
* 
~~~
{
  "account_name": "${account.name}",
  "policy_name": "${policy.name}",
  "events": [
  #foreach( $event in $fullEventList )
  {
  "guid": "$event.guid",
  "event_id": "${latestEvent.id}",
  "application_name": "${latestEvent.application.name}",
  "eventTypeKey": "$event.eventTypeKey",
  "severity": "$event.severity",
  "displayName": "$event.displayName",
  "summaryMessage": "$event.summaryMessage",
  "eventTime": "${event.eventTime}",
  "deepLink": "${event.deepLink}"
  }#if( $foreach.hasNext ),#end
  #end
  ],
  "topSeverity": "${topSeverity}",
  "controllerUrl": "${controllerUrl}",
  "action_name": "${action.name}"
}
~~~

**Comment by choonho** [comment]
# Example

* This is new creating event.

~~~
{
"account_name": "painted202303xxxxxxxxxx", 
"policy_name": "JAVA alert", 
"events": [
    {
        "guid": "c325f6b8-f065-4e14-a52d-xxxxxxxxxxx", 
        "event_id": "32343305", 
        "application_name": "MyApp", 
        "eventTypeKey": "Health Rule", 
        "severity": "ERROR", 
        "displayName": "New Critical Health Rule Violation", 
        "summaryMessage": "AppDynamics has detected a problem with Business Transaction <b>/manager/WEB-INF</b>.<br><b>Business Transaction Health</b> started violating and is now <b>critical</b>.", 
        "eventTime": "Mon Mar 27 02:03:55 UTC 2023", 
        "deepLink": "https://painted20230307xxxxxxxx.saas.appdynamics.com/#location=APP_EVENT_VIEWER_MODAL&eventSummary=32343305&application=108979"
        }
      ], 
  "topSeverity": "ERROR", 
  "controllerUrl": "https://painted202303071xxxxxx.saas.appdynamics.com", 
  "action_name": "spaceone-dev-test"
}
~~~

**Comment by choonho** [comment]
# Example

* This is ongoing event

~~~
{
  "account_name": "painted202303071xxxxxx", 
  "policy_name": "JAVA alert", 
  "events": [
      {
         "guid": "f4020056-6f21-4df4-802f-ccdd5daff62b", 
         "event_id": "32343365", 
         "application_name": "MyApp", 
         "eventTypeKey": "Health Rule", 
         "severity": "ERROR", 
         "displayName": "Ongoing Critical Health Rule Violation", 
         "summaryMessage": "AppDynamics has detected a problem with Business Transaction <b>/manager/WEB-INF</b>.<br><b>Business Transaction Health</b> continues to violate with <b>critical</b>.", 
          "eventTime": "Mon Mar 27 02:04:55 UTC 2023", 
          "deepLink": "https://painted202303071xxxxxxx.saas.appdynamics.com/#location=APP_EVENT_VIEWER_MODAL&eventSummary=32343365&application=108979"
          }], 
  "topSeverity": "ERROR", 
  "controllerUrl": "https://painted202303071xxxxxx.saas.appdynamics.com", 
  "action_name": "spaceone-dev-test"}
~~~

**Comment by choonho** [comment]
# Example

* This is cancel event (End of event)

~~~
{
  "account_name": "painted20230307xxxxxxx", 
  "policy_name": "JAVA alert", 
  "events": [
     {
     "guid": "1ea799aa-e522-452c-a88d-ef4df3df3b76", 
     "event_id": "32344175", 
     "application_name": "MyApp", 
     "eventTypeKey": "Health Rule", 
     "severity": "INFO", 
     "displayName": "Health Rule Canceled", 
     "summaryMessage": "Health Rule Business Transaction Health was cancelled", 
     "eventTime": "Mon Mar 27 02:19:55 UTC 2023", 
     "deepLink": "https://painted20230307xxxxxx.saas.appdynamics.com/#location=APP_EVENT_VIEWER_MODAL&eventSummary=32344175&application=108979"}
         ], 
  "topSeverity": "INFO", 
  "controllerUrl": "https://painted20230307xxxxxx.saas.appdynamics.com", 
  "action_name": "spaceone-dev-test"
}
~~~

**Comment by nkayal** [comment]
Regarding the topic of _merging related health rule incidents_, maybe consider using the AppD **"${latestEvent.incident.id}"** predefined template variable?

**"${latestEvent.incident.id}"** is a unique ID throughout the Health Rule cycle within the controller. This variable is only defined with the "healthRuleEvent == true" (i.e. only when the event type is health rule). Incident ID remains the same throughout the life cycle of Health rule event (i.e Started -> Warning ->continuous ->Critical->Warning -> Resolved).

As an example of this template implementation, please see: 


<img width="623" alt="Screenshot 2023-03-29 at 23 01 21" src="https://user-images.githubusercontent.com/12612812/228677531-42e39cfc-893a-4a83-864d-d4110cfbdc5c.png">

https://docs.appdynamics.com/appd/23.x/latest/en/appdynamics-essentials/alert-and-respond/actions/http-request-actions-and-templates/create-a-template-for-opsgenie

**Comment by choonho** [comment]
# Resolve the issue

Apply new payload.

![image](https://user-images.githubusercontent.com/3993088/229706560-8987345d-4204-48a5-aa4c-4b5601042f0f.png)

**Comment by choonho** [comment]
We use same payload like **opsgenie**

https://github.com/cloudforet-io/plugin-appdynamics-mon-webhook/blob/master/docs/en/README.md
